app:
  log_path: output/

redis:
  host: 127.0.0.1
  port: 6379
  username: ~
  password: ~
  db: 1

mysql:
  host: 127.0.0.1
  port: 3306
  username: admin
  password: admin123
  dbname: stock

ddl:
  path: data/ddl/
  tables:
    - kline
    - stock_info
    - stock_quote
    - stock_people
    - stock_block
    - stock_block_code
    - macd

xueqiu:
  init-num: 3000
  incr-num: 300
  cookie: xq_a_token=361dcfccb1d32a1d9b5b65f1a188b9c9ed1e687d; xqat=361dcfccb1d32a1d9b5b65f1a188b9c9ed1e687d; xq_r_token=450d1db0db9659a6af7cc9297bfa4fccf1776fae; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOi0xLCJpc3MiOiJ1YyIsImV4cCI6MTc1MzgzODAwNiwiY3RtIjoxNzUxODUzNjk1MDcyLCJjaWQiOiJkOWQwbjRBWnVwIn0.akXcNWOIANOjKwNYFmHJB-r2UBndAT74Mw2KTDC0PAfF7s0QETO88_PBWNP3h9nOVK8ybpFazKuGVf6eI0fL6suipXgFzxETE6OE5dw4M8PVOCud59juwaVnEIYb31GcPBED4nM0m0Pys-Q_p0knqofVuDC-yfmVNNTfWkpb07FWT76CN2-97VXrWDVIt-0z2NtNhltRcMvS5GLZcHFND_hqZkPDlt_ULqC4tjMlkWig_WeuiegvUXA3HccsFrf1MnicTCZgDpLfuiZegTDEQ4VIyUtTCpcmGkv3fumABJC-hjm9u7ZdjTbsG7V3PhDFig7jkAvJvzp8AG9rMJTfhQ; cookiesu=401751853703222; u=401751853703222; Hm_lvt_1db88642e346389874251b5a1eded6e3=1751853704; HMACCOUNT=4E241CB613976D73; device_id=11f0d3487798a014e99610b81a51d65e; is_overseas=0; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1751958650; ssxmod_itna=Yq0xcDnD9GKxyDRxeKYIBqW9YILDuWDYq0dGMRDeq7trGcD8OD0PGOIs3LzQUCWQDDI3KKif5E3DBwYoDSxD=7DK4GTmGhGi0m3zejHNIqmWhnDq34Rex+cAaN96b7aiimzr43hX9/l/7fKRb+eD884DKqGmD0=DAdqD7we4YxGGf4GwDGoD34DiDDpdxDUbpQqD7xnQMQWquB2omeWDm3wKPoqDmLHDnEcTTPWq5GaDff2a3=wexY6NztqrDPDLS1pvxB6KxYPpnCM6xBQ+1Q2OKcWWu0MuiGNeYhL4tb03YY4yfhhuShqdAK=xxmrseAKKY4K2QCEhmDDir4PAGob+8i+MWr2aUucAnaEuQDIYIr/Dp0pzemXjR3WXm0qsiDGlGxWwgE0Y0G8FeS1IYYD; ssxmod_itna2=Yq0xcDnD9GKxyDRxeKYIBqW9YILDuWDYq0dGMRDeq7trGcD8OD0PGOIs3LzQUCWQDDI3KKif5oDir8i0GmWiDxGaij78uGDBLbpE3fFrdaqT=AGMWXqb010W7rIFqh98phaxQZ2GhaUIxjwGXIuD6K0LUITigYlUnzL44eMxBzjU3fgRgfhdf/kUQ2qiNLB=7jjKNZw3YyQnD6qtaNen5ZeaHPnLle==79CaehuaNhc7+ZpXGWL3znfOdrGyg/6gIrBx+kUKnluLhoWIspLkNESCUVcdckXunSUtspzDx2KzSL46IqVilrie+IumP/SR94K7fGLIy4xTNRvIDq4eIvGxxmmCKF0zuz8YhzuKdTBjBM7KxkBWSIGnv49K/fxxjufIbei08AeVGuItp7j5C84wn+xGcDfYHAqiywE4bOCvTfbEie73DwY24si=U8u+GiIqpWw9QpHS8yDLI9bPBSx/fCzDpB4OOkQpTNgbu3bO34hidXlbz=TacTPU3c+IqGMtWDonSTz+r9rNS3xDRqQ34YhwOlr7+DD
etf:
  - name: 创业板ETF
    market: SZ
    code: 159915
  - name: 光伏ETF
    market: SH
    code: 515790

index:
  - name: 上证指数
    market: SH
    code: 1A0001
  - name: 深圳成指
    market: SZ
    code: 399001
  - name: 创业版指
    market: SZ
    code: 399006


