app:
  log_path: output/

redis:
  host: 127.0.0.1
  port: 6379
  username: ~
  password: ~
  db: 1

mysql:
  host: 127.0.0.1
  port: 3306
  username: admin
  password: admin123
  dbname: stock

ddl:
  path: data/ddl/
  tables:
    - kline
    - stock_info

xueqiu:
  init-num: 3000
  incr-num: 5
  cookie: cookiesu=331693906571177; device_id=8186d82194121188c1cd663d3ef9b95d; s=b412f8hns3; Hm_lvt_1db88642e346389874251b5a1eded6e3=1714147270; remember=1; xq_a_token=f34b0a1cfe0608e50052ecb5fb91eb72136831f2; xqat=f34b0a1cfe0608e50052ecb5fb91eb72136831f2; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOjUwMDUxNzYyNTUsImlzcyI6InVjIiwiZXhwIjoxNzE2NjI5MzM3LCJjdG0iOjE3MTQxNzk4MjQ4NTYsImNpZCI6ImQ5ZDBuNEFadXAifQ.lERHDqliUNJORU1LijF7lB0i0MAPOxQ0K7AeH4GHlikkurmjoG4-2gwu3OYgNWrUK_MPNQFXBQRJ7BVPyS3sIj-8Saxbo_RKqZXd93O7IY3b3E9j64zQc_yHh4H5NnEVLSCweOXkTEHAtAs615TB5_WwyS-cUTaZw8ce34qy1Mvbmg6tkvBW-5anZFzLFU99bCrnPsNB6692wmtTPU-gDibR07ZFrCKiQJ3PTkKn9bPYXj3iOEDj2-s6KBb6OD8y-hFoBpyjp1U4kTyDEwLXGnOtAK4rU_0bf3N70RPZ_35Mm5-D81F8zCI_DIqS5khLnM4KccBIxDUQaqHTIgc35g; xq_r_token=297ea2695cc0badb8b93ce7b90a2f513d75a9982; xq_is_login=1; u=5005176255; is_overseas=0; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1714189693

etf:
  - name: 创业板ETF
    market: SZ
    code: 159915
  - name: 光伏ETF
    market: SH
    code: 515790

index:
  - name: 上证指数
    market: SH
    code: 000001
  - name: 深圳成指
    market: SZ
    code: 399001
  - name: 创业版指
    market: SZ
    code: 399006


