app:
  log_path: output/

redis:
  host: 127.0.0.1
  port: 6379
  username: ~
  password: ~
  db: 1

mysql:
  host: 127.0.0.1
  port: 3306
  username: admin
  password: admin123
  dbname: stock

ddl:
  path: data/ddl/
  tables:
    - kline
    - stock_info
    - stock_quote
    - stock_people
    - stock_block
    - stock_block_code
    - macd

xueqiu:
  init-num: 3000
  incr-num: 10
  cookie: cookiesu=411732586388064; u=411732586388064; device_id=35a57f3aa3ebb44f481187f9d1687f99; Hm_lvt_1db88642e346389874251b5a1eded6e3=1732586390; HMACCOUNT=0C3BAB49B103F54A; s=bu15b6sbks; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1732874592; xq_a_token=220b0abef0fac476d076c9f7a3938b7edac35f48; xqat=220b0abef0fac476d076c9f7a3938b7edac35f48; xq_r_token=a57f65f14670a8897031b7c4f10ea42a50894850; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOi0xLCJpc3MiOiJ1YyIsImV4cCI6MTczNTY5Mjg4OSwiY3RtIjoxNzMzMTA5MzAyMjEwLCJjaWQiOiJkOWQwbjRBWnVwIn0.qi-izwF0_o6riBhOsTX9a2u2uS3nrgCBRysE2iuKbclOadiqvQkycynFP_LCuRM4Rvj-YeDiIy4lWTnpQ0ep2x75OcaGi5FVcx984vMGf76RJ-sCJnppzwVwypclV7d48Gn0libmSjlNU1NKDS0h0-m3T4J35bDxggJ3EyCnoKTanNnj9djRHLpkyzqluiVxZXIofIpNtvSP9UuhM4EFyfG5duAfZZYtalXpA_2dw-xs5o3nbGjSfKaa3G4PoBYw0A2owU5AvQeEIkCk2BfxGWlP9cnD8TS7hOsYvbMh7QiYFfHsRYHCVx5hd1VOHKKKDz-lnZ-uQSHsCidw8Lqy1Q; is_overseas=0; ssxmod_itna=YqAx9DBD2DcD0DRh2Dz=DUBUqf4Cq0QG3rGQiGYGWT1DlcixA5D8D6DQeGTW9eYtjB70woUzjbxx4tCx2rTpQ1g2xYHe1PWxPD=xYQDwxYoDUxGtDpxG=3YADYY1Dt4DTD34DYDixtDBlk6nDGplmutZS36u/86lDifn3qDRbqDgUeD1QeixuLLx3eGf3qGgld60DY=DQTcnIQNDjSRbaPGy3qGWCOUkXPGulnj0UGXV4Q=1EDmI8I+GKB=KGOeeGGoiQGGtWB8Nmt4U50qYmGlxCGdU948DG+xt44exD===; ssxmod_itna2=YqAx9DBD2DcD0DRh2Dz=DUBUqf4Cq0QG3rGQiGYGWTD6cfiDgD0vyDY033YzMRcDn4wCSerk7UGKxhnH0x/Dr0ERK3R=w9D5gBUuwx8YRrGobqK3b/qwIq24af4mQzbAdY2daq1irNifxpmS=bWSXEidvlKDEVbnrjS+D5V3YcQhI3urf87i=qYAAIKETwmCWqYSY1Ki=C/ju+CCnxYqehYqhrcqoYYpWm7qc56Rd44QYPDzoECCo+44+4VpijD22UCIF8nOglA3UzPdtE4CnGf/0pO6oP/uXUaYUkd+f/KDk5pKBwby1nYt7Lo1oNK+71ko7o33ldsrrxh=o44YOW/w3iodPhtVrxObCfxzP2x6DDwaqDjKDeLKwD59Gx4D
etf:
  - name: 创业板ETF
    market: SZ
    code: 159915
  - name: 光伏ETF
    market: SH
    code: 515790

index:
  - name: 上证指数
    market: SH
    code: 1A0001
  - name: 深圳成指
    market: SZ
    code: 399001
  - name: 创业版指
    market: SZ
    code: 399006


