app:
  log_path: output/

redis:
  host: 127.0.0.1
  port: 6379
  username: ~
  password: ~
  db: 1

mysql:
  host: 127.0.0.1
  port: 3306
  username: admin
  password: admin123
  dbname: stock

ddl:
  path: data/ddl/
  tables:
    - kline
    - stock_info
    - stock_quote
    - stock_people
    - stock_block
    - stock_block_code
    - macd

xueqiu:
  init-num: 3000
  incr-num: 10
  cookie: cookiesu=391737627758600; u=391737627758600; Hm_lvt_1db88642e346389874251b5a1eded6e3=1737627760; HMACCOUNT=D9E2CE5D9A562E9F; device_id=35a57f3aa3ebb44f481187f9d1687f99; smidV2=2025012318224447791f11dcc45ffc6af578c747c086880089d22a9fb005540; s=bl11l9m12s; .thumbcache_f24b8bbe5a5934237bbc0eda20c1b6e7=qjN8m58K+nuOhG6JohYYOcQEnyNaSGzoQ/SYhcpNBBMF6xOwxBtnxfyn2jr/ewqPf9Qx8Ls0cfohhG6WHPwUrg%3D%3D; acw_tc=ac11000117387189689775804e00614e6488b05be3d739219863cd69e996e8; xq_a_token=b1d767edc014ddf478005982ba9e053910dad8dc; xqat=b1d767edc014ddf478005982ba9e053910dad8dc; xq_r_token=4ac6dcb5a1bd823260eef986e5e529b07195748d; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOi0xLCJpc3MiOiJ1YyIsImV4cCI6MTc0MDg3NzAzNywiY3RtIjoxNzM4NzE4OTM2Mzc1LCJjaWQiOiJkOWQwbjRBWnVwIn0.RSYBq0qzX1nYUHef7ZzY-0EiHWqIc8qk-AOe6CEzjkOixqJIA3EkvwOV4G8iVD-9rYDXcYZVju6shdb_p3K9Hf3XuG3fFSRtLOZtkklUSe4ZkwrDrsUu9QQa5PB2RPWgU66iNB-JWSOiq_9Wq2OxrIMt1vhiQ7bP_rFwC7p_viR4KkcHLvgK2pAkj6f0_A4dPh6OcUmPIjDijXPRL5UjLhXwWrOlR--u_VXOpIDOZJ-KnJIDY2f71AIuy3rWXBJiRS-aY0-o9SLlCZjGRCJD97c0MsCB-1e4dChzNA8tQ8r9kUAB-kmwlj5EgYvMD22R6rM2jd87z7tK_9D51OGQ9Q; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1738718971; ssxmod_itna=YqAxgD2DBDu0DQoi7YuOYxIxUxWquD0dGMD3qiQGgDYq7=GFKDCOIO=eOwrOk27MreD9e+2DCDBqrviDnqD8XDQeDv4Z+G+5Be4jq+335joxt4ezGniimZQnIZGtYTwBCSck5CeiTbDQKDoxGkDiHoD0FY3e4DxrPD5xDTDWeDGDD3=4DCk+7oD0+pNtgplabhbGApDYaoqUboDYyjDAuA1/Epl=GADWcGEjOoVxi8OWCoL7oDF=k3Pq0kq4i3YxOnrq0OSbBsRmovzF4cPpKehA5wuhDq/GKq4rDt/j2D8OhgYlDN3D9lYY1BiGDDfinh6AviiDeiej66U=AX6YC0Dp0KeAeSWeMom5nxh0qrCmCjwzAGs7XZ1iq7DgOXtCm5YD; ssxmod_itna2=YqAxgD2DBDu0DQoi7YuOYxIxUxWquD0dGMD3qiQGgDYq7=GFKDCOIO=eOwrOk27MreD9e+2GiDG3nG5Y46hDxDLQi2qf=x0ycLQetYkj=W5i9G+0QiY1Qm0qSY=IWKe4kizkKkpwGxZ=R8fH/T6tbkiBAkXHY7jHef0qsxhR+xNwR8=3HLt=vfdeR44EiAuZf+3hAqQeI+GRCkUtI3uLzrhbwSTgK7cQLANQPPhBe3y35iWCVTgPqkxEfPjH+LifHdH5zqdSjM3HsUj2RrnxzlH0YGdF516+k5XGum0b2m2A=ckAu6dKuPbpbxAoKjwzZAH1+8kDN=3Who3REtNwbL3K2+r2hb2SkbWGx+b6rNXotqYFWLqLED6wi6gOHhDzh=0x8Wh+FfTNYeSCvIjx8bxe7oMmA5o5MA53B5kiOSnEecE4D
etf:
  - name: 创业板ETF
    market: SZ
    code: 159915
  - name: 光伏ETF
    market: SH
    code: 515790

index:
  - name: 上证指数
    market: SH
    code: 1A0001
  - name: 深圳成指
    market: SZ
    code: 399001
  - name: 创业版指
    market: SZ
    code: 399006


