app:
  log_path: output/

redis:
  host: 127.0.0.1
  port: 6379
  username: ~
  password: ~
  db: 1

mysql:
  host: 127.0.0.1
  port: 3306
  username: admin
  password: admin123
  dbname: stock

ddl:
  path: data/ddl/
  tables:
    - kline
    - stock_info
    - stock_quote
    - stock_people
    - stock_block
    - stock_block_code
    - macd

xueqiu:
  init-num: 3000
  incr-num: 10
  cookie: xq_a_token=691d6f0a678b98a172affb89759b9c46fd23b4e2; xqat=691d6f0a678b98a172affb89759b9c46fd23b4e2; xq_r_token=de180625dcdde2e538953eb202d55300cae40fe1; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOi0xLCJpc3MiOiJ1YyIsImV4cCI6MTczNDM5Njg3MiwiY3RtIjoxNzMxODkzNjE0NjQ5LCJjaWQiOiJkOWQwbjRBWnVwIn0.f0vdL89kruGHFA4rT168NS--ha38uzaIISMUxl14agLPivX1ngwooiQN672Lm8jJzVa4EvMgNLlnMG_bslzsrPKk9l_7E7j6W0csikNtG-Rkw6rRuAxwunNGEvabHaOuvamMNAtRa157E5lq4ZL2XKv5-NwsC-OoymPWjP8EQlqcLr0DbJyIRxDoCvr97FrfGcRGsMpReFaZ1Vlt9VSrJR-0d8KleG3nO8g1A1lYrKPWYkW6T4Q8qyWmiQCY0elaLv-CD7UeEmJdqZZUJs9JzYt3Sx-ocSs1k5WevVJl_LzVSFFlL6yRQqHAFr6L_CLadBRtJv65rVqNtGb2eHQFmw; cookiesu=761731893643699; u=761731893643699; Hm_lvt_1db88642e346389874251b5a1eded6e3=1731893646; HMACCOUNT=39AB4ED41D6FC6FC; device_id=35a57f3aa3ebb44f481187f9d1687f99; s=aj111xwd01; is_overseas=0; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1731893680; ssxmod_itna=QqjxgGKYqLGH3GdD7+NiQGkKHDtI+Qq4D8ICYSCUDBM4AK5DZDiqAPGhDCR2IjMm+o3z=gcdFP5j+moFKIQ2aTEOIQGPrFvUBDiTD4q07Db4GkDAqiOD7uh3DxEq0rD74irDDxD30xDvsjEKDjmvC9EvHfhK7jp5DbEIODiI8DYypDAwhD37zzEihDWpODQvsfoKDExGOff9mgxGaHFffDlIODm4du1M6DCIvvoFelZHGfELqqYautem3Y1x5s7bxmj+5Kmh4DOi93Y+xXYUi1cPHiqDWena9qYD; ssxmod_itna2=QqjxgGKYqLGH3GdD7+NiQGkKHDtI+Qq4D8ICYSD8T6dPGN4OGaKQDfO96Mpn7Kid8fEBaIoxV=7iQm4LrSp44cf1MpR8HzpTxWEuUWwguQsx8/+BpXDb8Ft9Nw5PgPXqRl4OtbeSPm4L2m5xpyHHBm8sZKi2amHDhH1x=Bzat9pDrcDWS7It2oTrU9smfPGsRFmqmE7NcgpYprrY25oQgezVEYr8UIxVtqozUFW+heocKF=T0w1O3E491T8+WnIumlek6EOqnr=xqW5K5Z=+Z=OCe7nyPWCetqxqmu1UYPafRmxhwnDPEq6SiPBP18Q=dKF2Hs+3TM3Ngsmg5bj=ALbLxkOAraMQju=3EY=+1jgKhT8O3qX8rDWPD7QNnhol+e=wPQ0dip7tuP1T6AuoWm8UGy0xmYwGcTPWnhIxDjKDekI3M4rhz4D=
etf:
  - name: 创业板ETF
    market: SZ
    code: 159915
  - name: 光伏ETF
    market: SH
    code: 515790

index:
  - name: 上证指数
    market: SH
    code: 1A0001
  - name: 深圳成指
    market: SZ
    code: 399001
  - name: 创业版指
    market: SZ
    code: 399006


