app:
  log_path: output/

redis:
  host: 127.0.0.1
  port: 6379
  username: ~
  password: ~
  db: 1

mysql:
  host: 127.0.0.1
  port: 3306
  username: admin
  password: admin123
  dbname: stock

ddl:
  path: data/ddl/
  tables:
    - kline
    - stock_info
    - stock_quote
    - stock_people
    - stock_block
    - stock_block_code
    - macd

xueqiu:
  init-num: 3000
  incr-num: 5
  cookie: cookiesu=461702884584253; device_id=4d18972fa137777aa41d72272920fe74; xq_is_login=1; u=5005176255; s=at11itg18z; bid=80cf8bf2b7008be8c0f9a86236354f1a_lqx5gx4a; Hm_lvt_1db88642e346389874251b5a1eded6e3=1715076701,1715847083,1715924128,1716372576; xq_a_token=1b5ccac4dfb9d02312bf5766542bd22eaef48196; xqat=1b5ccac4dfb9d02312bf5766542bd22eaef48196; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOjUwMDUxNzYyNTUsImlzcyI6InVjIiwiZXhwIjoxNzE5OTc3MzgzLCJjdG0iOjE3MTczODUzODM0ODAsImNpZCI6ImQ5ZDBuNEFadXAifQ.kxvQmJh8u3rehewDdE8vx0nGjyDjaGB8bMoeWo_3j7XHM5F5ixYLxSNm-M9GLepL1XE_PTEFJ_jqsCOuIbWF0Y1lk2M77afNtSvJHRdY1O7VOuxfr_zRc-zBibQM87Obdkwm4Bv2jkGv70OnTlwPPAEqcoLiQfYLhoxVMQBowurF0d_ADWP3NGV0wgnM8PqUNJ_-FeVijWDeCdCq9t-d8VVDNotwrGEftAlCg5RsCJTjHhaDTOWfw9RCWoFyUnx3AnryVJM0twwadb96xrkiZDUTdLBDeseLWHLqd60CrqCY73FFKwu365ywlQNMmG2qPfri-JEjMr6pLWfiAoF17w; xq_r_token=3878684608feda3c297ee1a092f556bbb841df02; is_overseas=0; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1717385623
etf:
  - name: 创业板ETF
    market: SZ
    code: 159915
  - name: 光伏ETF
    market: SH
    code: 515790

index:
  - name: 上证指数
    market: SH
    code: 1A0001
  - name: 深圳成指
    market: SZ
    code: 399001
  - name: 创业版指
    market: SZ
    code: 399006


