app:
  log_path: output/

redis:
  host: 127.0.0.1
  port: 6379
  username: ~
  password: ~
  db: 1

mysql:
  host: 127.0.0.1
  port: 3306
  username: admin
  password: admin123
  dbname: stock

ddl:
  path: data/ddl/
  tables:
    - kline
    - stock_info
    - stock_quote
    - stock_people
    - stock_block
    - stock_block_code
    - macd

xueqiu:
  init-num: 3000
  incr-num: 10
  cookie: cookiesu=701735090574662; device_id=371b0d8624aedd8ca28c2ae5ddbd0448; xq_a_token=b813a12eb0682b072cce896e4e6c985ecd8efdbd; xqat=b813a12eb0682b072cce896e4e6c985ecd8efdbd; xq_r_token=d910de90c340f87c9dd5e734c5eb96861ad7740a; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOi0xLCJpc3MiOiJ1YyIsImV4cCI6MTc1NjQzMDAzMCwiY3RtIjoxNzU0NjQ1NzYzMTcxLCJjaWQiOiJkOWQwbjRBWnVwIn0.Tdx2ZTYiTKqFwlP1rtLJ_PmDxqlDpgNFu1MGRW99VkB5zCz6oE0w2U0mCEcumYIycb-QCylHYItQdFVzJ3aI0cwEtgtl2x1kUXD8cYi0RQiw4U9aCNWLY5zClVY10vbWtUry5UuN-_UnDlPdm2MvkZGU9Pv19t--T3zTM95ipsGV6zI15SeiLWMi0wNq8ucYKLZ5bzsY__C6q4AVm_s2R0n36cg1e36fWUO9OMg1U4JE_uFcvhRGwi6bDOIsH5q0gi7ML8sOCVoA6pggPG0tkFLUnbFEvfMihU5HK56x0FzDibhvqeRX01RuO6V1ZdLA6MIVyoolIpBjimKDtOewuA; u=701735090574662; Hm_lvt_1db88642e346389874251b5a1eded6e3=1754645766; HMACCOUNT=D3D2EE277D3B8753; is_overseas=0; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1754706329; ssxmod_itna=1-iqGx2D97i=dYqqeIxmqD5dpiED2DpOxBP01s1DuxiK08D6BDB40Q2KeUDwE38DCu_x/YG7Iqdq5guiNDl2ieDZDGIdDqx0orUK7hiNeqH000T5/A0n24eeztA0uP/i7zF1HKK0AEL5F8869zdtx1uDwIrmxexGI_Y5Db4DyDGUNDG=rKxGG04GwDGoD34DiDDPtxDta2lqD7EWNPcnKVARY0jWDmSwoagqDmT7DnrFF16nK1YFDf8bWWZwCDY=DQwSNWEWDjb7WAKGyIeGW8Su0q5GubIRC_xcakZqRP2hx4m2XtbmPz8Kqmh4C5K6KqBD3QG_Dp3jGMBq5jhzY_X0mXDDAS2xFmZFW4exSFHMInM9mZC0ViOOlrT/R7Y0iGg=eh_/riKbrIxPeWVBD4eR8CDP65PeD; ssxmod_itna2=1-iqGx2D97i=dYqqeIxmqD5dpiED2DpOxBP01s1DuxiK08D6BDB40Q2KeUDwE38DCu_x/YG7Iqdq5guGYDio4hXryUx7pOuiWcGwxuD0vdKa5C1i7Ua1CPjdsao7tlQBjrHajZl2rGBz/OtqKlQiUlDj=SCEQj4k=HFiUBKj2ZjkRc4lLodj24wM5q/3RlK0N3YnUyDljRilLN6dF=x6fKFBdW=A0x0=6sjq4c_WTL9cUYOej7VgQqjDXRlSLO3juu4CdAkQdczLr5FT7=cR3NLbLKLaT544XUWunu_nhnP=XRv/r5_qCQuWWF7bdATdTd0G4XOHonrPi=H25Ao=nOKF7tuRxhrdZdwFM3OjQEdwiLT1CGsldiu=HrW5m7GgGWjwEfd_fk_2zsxxfCQKrv33TOjkZjw3ea/n7sdwr8_OC=8oCWBd6da8R5XOx8EDo_Dkq8qBzVB=0kKrnPW7=Duvi3ttiIbj33eoAEQKG_yLxagAei_AbQx=Qol15=wUYk0GwArr5uv7_pwft=8jNItIL=FhsAWQmlAh6CkTiwhfuGX_EitiE8W=ZLnEZ8kftldwTSk6Ii14XebOt4NeLnP8rbffuUt7D9i4pDV6Dy8KBQ2Esqiehkx/A52g4eU66d_5dMseWe0m9_j5E34n5bZ7NGrIsHeiee7xe05/OHM8S2HVuA5DrYexdiLjbVGN5YVQDxD

etf:
  - name: 创业板ETF
    market: SZ
    code: 159915
  - name: 光伏ETF
    market: SH
    code: 515790
  - name: 半导体
    market: SH
    code: 512480

index:
  - name: 上证指数
    market: SH
    code: 1A0001
  - name: 深圳成指
    market: SZ
    code: 399001
  - name: 创业版指
    market: SZ
    code: 399006


